version: '2'
services:
  web:
    image: arachniweblocal
    ports:
      - 9292:9292
    depends_on: 
      - dispatcher
    links: 
      - dispatcher
    volumes:
      - ./arachniWeb:/home/arachniwebreport
  dispatcher:
    image: arachnirpcdlocal
  dispatcher_grid:
    image: arachnirpcdlocal
    depends_on: 
      - dispatcher
    links: 
      - dispatcher
    command: "--neighbour=dispatcher:7331"
